export const CATEGORY_SET='CATEGORY_SET'
export const CATEGORIES_SET='CATEGORIES_SET'
export const CATEGORY_DELETE="CATEGORY_DELETE"
export const CATEGORY_STATE_CLEAR="CATEGORY_STATE_CLEAR"


export const COMMON_EROR_SET="COMMON_EROR_SET"
export const COMMON_MESSAGE_SET="COMMON_MESSAGE_SET"
export const COMMON_LOADING_SET="COMMON_LOADING_SET"

export const TITLE_SET='TITLE_SET'