export const CATEGORY_SET='CATEGORY_SET'
export const CATEGORIES_SET='CATEGORIES_SET'
export const CATEGORY_DELETE="CATEGORY_DELETE"
export const CATEGORY_STATE_CLEAR="CATEGORY_STATE_CLEAR"

export const BRAND_SET='BRAND_SET'
export const BRANDS_SET='BRANDS_SET'
export const BRAND_DELETE="BRAND_DELETE"
export const BRAND_UPDATE="BRAND_UPDATE"
export const BRAND_STATE_CLEAR="BRAND_STATE_CLEAR"
export const BRAND_APPEND='BRAND_APPEND'
export const BRAND_SET_PAGEABLE='BRAND_SET_PAGEABLE'




export const COMMON_EROR_SET="COMMON_EROR_SET"
export const COMMON_MESSAGE_SET="COMMON_MESSAGE_SET"
export const COMMON_LOADING_SET="COMMON_LOADING_SET"

export const TITLE_SET='TITLE_SET'