export const CATEGORY_SET='CATEGORY_SET'
export const CATEGORIES_SET='CATEGORIES_SET'
export const CATEGORY_DELETE="CATEGORY_DELETE"
export const CATEGORY_STATE_CLEAR="CATEGORY_STATE_CLEAR"
export const CATEGORY_UPDATE="CATEGORY_UPDATE"
export const CATEGORY_APPEND='CATEGORY_APPEND'
export const CATEGORY_SET_PAGEABLE='CATEGORY_SET_PAGEABLE'
export const CATEGORY_GET_PARENT = 'CATEGORY_GET_PARENT'
export const CATEGORY_GET_SORTORDER='CATEGORY_GET_SORTORDER'


export const BRAND_SET='BRAND_SET'
export const BRANDS_SET='BRANDS_SET'
export const BRAND_DELETE="BRAND_DELETE"
export const BRAND_UPDATE="BRAND_UPDATE"
export const BRAND_STATE_CLEAR="BRAND_STATE_CLEAR"
export const BRAND_APPEND='BRAND_APPEND'
export const BRAND_SET_PAGEABLE='BRAND_SET_PAGEABLE'


export const PRODUCT_SET='PRODUCT_SET'
export const PRODUCTS_SET='PRODUCTS_SET'
export const PRODUCT_APPEND='PRODUCT_APPEND'
export const PRODUCT_DELETE='PRODUCT_DELETE'
export const PRODUCT_UPDATE='PRODUCT_UPDATE'
export const PRODUCT_SET_PAGEABLE='PRODUCT_SET_PAGEABLE'
export const PRODUCT_STATE_CLEAR='PRODUCT_STATE_CLEAR'


export const COMMON_EROR_SET="COMMON_EROR_SET"
export const COMMON_MESSAGE_SET="COMMON_MESSAGE_SET"
export const COMMON_LOADING_SET="COMMON_LOADING_SET"
export const COMMON_MODAL_SET="COMMON_MODAL_SET"

export const TITLE_SET='TITLE_SET'